// Map
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION'

// Features
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS'
export const FETCH_FEATURES_PENDING = 'FETCH_FEATURES_PENDING'
export const FETCH_FEATURES_FAILED = 'FETCH_FEATURES_FAILED'
