version: 2.1

commands:
  install-dependencies:
    steps:
      - run:
          name: Add third-party repositories
          command: |
            # terraform
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository -y "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            # ansible
            sudo add-apt-repository -y --update ppa:ansible/ansible
      - run:
          name: Install necessary dependencies
          command: |
            sudo apt update
            sudo apt install tar gzip curl software-properties-common
  build:
    parameters:
      image_name:
        type: string
      folder_path:
        type: string
    steps:
      - run:
          name: Login to Dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build images
          command: docker build -t "$CIRCLE_USERNAME/geoapp_<< parameters.image_name >>" << parameters.folder_path >>
      - run:
          name: Push images
          command: docker push "$CIRCLE_USERNAME/geoapp_<< parameters.image_name >>"
  destroy-environment:
    parameters:
      workflow_id:
        type: string
    steps:
      - run:
          name: Destroy environment
          when: on_fail
          command: echo "Destroying environment..."

jobs:
  build-farmacie:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: farmacie
          folder_path: ./app_farmacie
  build-parchi:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: parchi
          folder_path: ./app_parchi
  build-popolazione:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: popolazione
          folder_path: ./app_popolazione
  build-punti-interesse:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: punti_interesse
          folder_path: ./app_punti_interesse
  build-scuole:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: scuole
          folder_path: ./app_scuole
  build-geoserver:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: geoserver
          folder_path: ./geoserver
  build-nginx:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - build:
          image_name: nginx
          folder_path: ./infra/nginx

  provision:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Install terraform
          command: sudo apt install terraform
      - run:
          name: Provision infrastructure
          command: echo "Provisioning..."

  configure:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - install-dependencies
      - add_ssh_keys:
          fingerprints:
            - 'b5:f4:85:77:e1:ad:c2:fb:78:ef:49:cd:c8:60:41:e5'
      - run:
          name: Install ansible
          command: sudo apt install ansible
      - run:
          name: Configure infrastructure
          command: |
            cd infra/ansible/
            ansible-playbook configure.yaml

  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - install-dependencies
      - add_ssh_keys:
          fingerprints:
            - 'b5:f4:85:77:e1:ad:c2:fb:78:ef:49:cd:c8:60:41:e5'
      - run:
          name: Install ansible
          command: sudo apt install ansible
      - run:
          name: Deploy apps
          command: |
            cd infra/ansible/
            ansible-playbook deploy.yaml

  smoke-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Request domain
          command: |
            URL="http://devopslabs.xyz"
            if curl -s $URL | grep "Farmacie a Verona"; then
              exit 0
            else
              exit 1
            fi

  cleanup:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "Cleaning..."

workflows:
  default:
    jobs:
      - build-farmacie
      - build-parchi
      - build-popolazione
      - build-punti-interesse
      - build-scuole
      - build-geoserver
      - build-nginx
      - configure:
          requires:
            - build-farmacie
            - build-parchi
            - build-popolazione
            - build-punti-interesse
            - build-scuole
            - build-geoserver
            - build-nginx
      - deploy:
          requires:
            - configure
      - smoke-test:
          requires:
            - deploy
      - cleanup:
          requires:
            - smoke-test
