FROM node:14-alpine

ENV REACT_APP_GEOSERVER_URL="http://geoserver.devopslabs.xyz"
ENV REACT_APP_GEOSERVER_WORKSPACE="geoapp-dev"

WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY ./ ./

CMD ["npm", "run", "start"]