---
- name: Install packages
  hosts: default
  become: yes
  tasks:
    - name: Fetch nodejs 14 binaries
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - name: Install pip, node, docker, docker-compose
      apt:
        pkg:
          - python3-pip
          - nodejs
          - docker.io
          - docker-compose
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name:
          - docker
          - docker-compose

- name: Add ubuntu to docker group
  hosts: default
  become: yes
  tasks:
    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Clone the git repository
  hosts: default
  tasks:
    - name: Clone git repository
      git:
        repo: https://github.com/ahmedaidev/geoapp-latest.git
        dest: /home/ubuntu/
