// Map
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION'
export const SHOW_LOCATION_MODAL = 'SHOW_LOCATION_MODAL'
export const DISMISS_LOCATION_MODAL = 'DISMISS_LOCATION_MODAL'

// Locations
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS'
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS'
