// Map
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION'
export const SHOW_LOCATION_MODAL = 'SHOW_LOCATION_MODAL'
export const DISMISS_LOCATION_MODAL = 'DISMISS_LOCATION_MODAL'

// Features
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS'
export const FETCH_FEATURES_PENDING = 'FETCH_FEATURES_PENDING'
export const FETCH_FEATURES_FAILED = 'FETCH_FEATURES_FAILED'
